=== cake-lier/PPS-20-caw/src/main/resources/board_schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "uuid:01548282-5443-4069-b8d3-8a6651d81211",
    "title": "Board",
    "description": "A board used in a level of the game",
    "type": "object",
    "properties": {
        "width": {
            "description": "The width of the board",
            "type": "integer",
            "minimum": 2,
            "maximum": 30
        },
        "height": {
            "description": "The height of the board",
            "type": "integer",
            "minimum": 2,
            "maximum": 30
        },
        "playableArea": {
            "description": "The area of the board in which the cells can be moved by the player",
            "type": "object",
            "properties": {
                "width": {
                    "description": "The width of the playable area",
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 30
                },
                "height": {
                    "description": "The height of the playable area",
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 30
                },
                "x": {
                    "description": "The x coordinate of the upper left corner of the playable area",
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 29
                },
                "y": {
                    "description": "The y coordinate of the upper left corner of the playable area",
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 29
                }
            },
            "additionalProperties": false,
            "required": [ "width", "height", "x", "y" ]
        },
        "cells": {
            "description": "The cells that are present on this board",
            "type": "object",
            "properties": {
                "mover": {
                    "description": "The push cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "orientation": {
                                "description": "The orientation of the push cell",
                                "enum": [ "right", "left", "top", "down" ]
                            },
                            "x": {
                                "description": "The x coordinate of the push cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the push cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "orientation", "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "generator": {
                    "description": "The generate cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "orientation": {
                                "description": "The orientation of the generate cell",
                                "enum": [ "right", "left", "top", "down" ]
                            },
                            "x": {
                                "description": "The x coordinate of the generate cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the generate cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "orientation", "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "rotator": {
                    "description": "The rotate cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "rotation": {
                                "description": "The direction of the rotate cell",
                                "enum": [ "clockwise", "counterclockwise" ]
                            },
                            "x": {
                                "description": "The x coordinate of the rotate cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the rotate cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "rotation", "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "block": {
                    "description": "The block cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "push": {
                                "description": "The direction in which the block cell allows to be pushed",
                                "enum": [ "horizontal", "vertical", "both" ]
                            },
                            "x": {
                                "description": "The x coordinate of the block cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the block cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "push", "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "enemy": {
                    "description": "The enemy cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "x": {
                                "description": "The x coordinate of the enemy cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the enemy cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "wall": {
                    "description": "The wall cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "x": {
                                "description": "The x coordinate of the wall cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the wall cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "x", "y" ]
                    },
                    "uniqueItems": true
                },
                "deleter": {
                    "description": "The deleter cells that are present on this board",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "x": {
                                "description": "The x coordinate of the deleter cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            },
                            "y": {
                                "description": "The y coordinate of the deleter cell",
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 29
                            }
                        },
                        "additionalProperties": false,
                        "required": [ "x", "y" ]
                    },
                    "uniqueItems": true
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false,
    "required": [ "width", "height", "playableArea", "cells" ]
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level09.json
{
  "width": 20,
  "height": 12,
  "playableArea": {
    "width": 18,
    "height": 3,
    "x": 1,
    "y": 1
  },
  "cells": {
    "mover": [
      {
        "x": 7,
        "y": 1,
        "orientation": "down"
      },
      {
        "x": 1,
        "y": 5,
        "orientation": "right"
      },
      {
        "x": 5,
        "y": 1,
        "orientation": "down"
      }
    ],
    "block": [
      {
        "x": 2,
        "y": 5,
        "push": "both"
      },
      {
        "x": 3,
        "y": 1,
        "push": "horizontal"
      }
    ],
    "enemy": [
      {
        "x": 9,
        "y": 9
      }
    ],
    "rotator": [
      {
        "x": 3,
        "y": 2,
        "rotation": "clockwise"
      },
      {
        "x": 6,
        "y": 5,
        "rotation": "clockwise"
      },
      {
        "x": 4,
        "y": 5,
        "rotation": "clockwise"
      },
      {
        "x": 7,
        "y": 5,
        "rotation": "clockwise"
      },
      {
        "x": 5,
        "y": 5,
        "rotation": "clockwise"
      },
      {
        "x": 3,
        "y": 5,
        "rotation": "clockwise"
      }
    ],
    "wall": [
      {
        "x": 0,
        "y": 0
      },
      {
        "x": 0,
        "y": 11
      },
      {
        "x": 1,
        "y": 0
      },
      {
        "x": 1,
        "y": 11
      },
      {
        "x": 2,
        "y": 0
      },
      {
        "x": 2,
        "y": 11
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": 11
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 11
      },
      {
        "x": 5,
        "y": 0
      },
      {
        "x": 5,
        "y": 11
      },
      {
        "x": 6,
        "y": 0
      },
      {
        "x": 6,
        "y": 11
      },
      {
        "x": 7,
        "y": 0
      },
      {
        "x": 7,
        "y": 11
      },
      {
        "x": 8,
        "y": 0
      },
      {
        "x": 8,
        "y": 11
      },
      {
        "x": 9,
        "y": 0
      },
      {
        "x": 9,
        "y": 11
      },
      {
        "x": 10,
        "y": 0
      },
      {
        "x": 10,
        "y": 11
      },
      {
        "x": 11,
        "y": 0
      },
      {
        "x": 11,
        "y": 11
      },
      {
        "x": 12,
        "y": 0
      },
      {
        "x": 12,
        "y": 11
      },
      {
        "x": 13,
        "y": 0
      },
      {
        "x": 13,
        "y": 11
      },
      {
        "x": 14,
        "y": 0
      },
      {
        "x": 14,
        "y": 11
      },
      {
        "x": 15,
        "y": 0
      },
      {
        "x": 15,
        "y": 11
      },
      {
        "x": 16,
        "y": 0
      },
      {
        "x": 16,
        "y": 11
      },
      {
        "x": 17,
        "y": 0
      },
      {
        "x": 17,
        "y": 11
      },
      {
        "x": 18,
        "y": 0
      },
      {
        "x": 18,
        "y": 11
      },
      {
        "x": 19,
        "y": 0
      },
      {
        "x": 19,
        "y": 11
      },
      {
        "x": 0,
        "y": 1
      },
      {
        "x": 0,
        "y": 2
      },
      {
        "x": 0,
        "y": 3
      },
      {
        "x": 0,
        "y": 4
      },
      {
        "x": 0,
        "y": 5
      },
      {
        "x": 0,
        "y": 6
      },
      {
        "x": 0,
        "y": 7
      },
      {
        "x": 0,
        "y": 8
      },
      {
        "x": 0,
        "y": 9
      },
      {
        "x": 0,
        "y": 10
      },
      {
        "x": 19,
        "y": 1
      },
      {
        "x": 19,
        "y": 2
      },
      {
        "x": 19,
        "y": 3
      },
      {
        "x": 19,
        "y": 4
      },
      {
        "x": 19,
        "y": 5
      },
      {
        "x": 19,
        "y": 6
      },
      {
        "x": 19,
        "y": 7
      },
      {
        "x": 19,
        "y": 8
      },
      {
        "x": 19,
        "y": 9
      },
      {
        "x": 19,
        "y": 10
      }
    ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level23.json
{
  "width" : 8,
  "height" : 16,
  "playableArea" : {
    "width" : 6,
    "height" : 5,
    "x" : 1,
    "y" : 7
  },
  "cells" : {
    "mover" : [ {
      "x" : 2,
      "y" : 7,
      "orientation" : "right"
    }, {
      "x" : 3,
      "y" : 8,
      "orientation" : "top"
    } ],
    "block" : [ {
      "x" : 3,
      "y" : 7,
      "push" : "both"
    } ],
    "rotator" : [ {
      "x" : 4,
      "y" : 5,
      "rotation" : "clockwise"
    }, {
      "x" : 3,
      "y" : 10,
      "rotation" : "clockwise"
    } ],
    "enemy" : [ {
      "x" : 4,
      "y" : 14
    }, {
      "x" : 3,
      "y" : 2
    }, {
      "x" : 4,
      "y" : 12
    }, {
      "x" : 4,
      "y" : 13
    } ],
    "wall" : [ {
      "x" : 7,
      "y" : 5
    }, {
      "x" : 4,
      "y" : 0
    }, {
      "x" : 3,
      "y" : 15
    }, {
      "x" : 7,
      "y" : 11
    }, {
      "x" : 7,
      "y" : 12
    }, {
      "x" : 7,
      "y" : 7
    }, {
      "x" : 4,
      "y" : 15
    }, {
      "x" : 7,
      "y" : 8
    }, {
      "x" : 5,
      "y" : 2
    }, {
      "x" : 7,
      "y" : 13
    }, {
      "x" : 7,
      "y" : 14
    }, {
      "x" : 0,
      "y" : 4
    }, {
      "x" : 0,
      "y" : 11
    }, {
      "x" : 0,
      "y" : 12
    }, {
      "x" : 1,
      "y" : 14
    }, {
      "x" : 0,
      "y" : 6
    }, {
      "x" : 5,
      "y" : 15
    }, {
      "x" : 0,
      "y" : 14
    }, {
      "x" : 6,
      "y" : 15
    }, {
      "x" : 0,
      "y" : 13
    }, {
      "x" : 0,
      "y" : 9
    }, {
      "x" : 1,
      "y" : 15
    }, {
      "x" : 2,
      "y" : 15
    }, {
      "x" : 0,
      "y" : 5
    }, {
      "x" : 6,
      "y" : 3
    }, {
      "x" : 7,
      "y" : 9
    }, {
      "x" : 7,
      "y" : 10
    }, {
      "x" : 7,
      "y" : 4
    }, {
      "x" : 5,
      "y" : 0
    }, {
      "x" : 0,
      "y" : 8
    }, {
      "x" : 4,
      "y" : 1
    }, {
      "x" : 1,
      "y" : 3
    }, {
      "x" : 0,
      "y" : 10
    }, {
      "x" : 0,
      "y" : 7
    }, {
      "x" : 7,
      "y" : 6
    }, {
      "x" : 3,
      "y" : 0
    }, {
      "x" : 2,
      "y" : 2
    }, {
      "x" : 3,
      "y" : 1
    }, {
      "x" : 6,
      "y" : 14
    }, {
      "x" : 2,
      "y" : 0
    } ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level10.json
{
  "width": 15,
  "height": 7,
  "playableArea": {
    "width": 5,
    "height": 5,
    "x": 5,
    "y": 1
  },
  "cells": {
    "generator": [
      {
        "x": 7,
        "y": 2,
        "orientation": "right"
      },
      {
        "x": 8,
        "y": 5,
        "orientation": "left"
      }
    ],
    "block": [
      {
        "x": 5,
        "y": 3,
        "push": "vertical"
      }
    ],
    "enemy": [
      {
        "x": 12,
        "y": 3
      },
      {
        "x": 3,
        "y": 3
      }
    ],
    "wall": [
      {
        "x": 9,
        "y": 4
      },
      {
        "x": 0,
        "y": 0
      },
      {
        "x": 0,
        "y": 6
      },
      {
        "x": 1,
        "y": 0
      },
      {
        "x": 1,
        "y": 6
      },
      {
        "x": 2,
        "y": 0
      },
      {
        "x": 2,
        "y": 6
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": 6
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 6
      },
      {
        "x": 5,
        "y": 0
      },
      {
        "x": 5,
        "y": 6
      },
      {
        "x": 6,
        "y": 0
      },
      {
        "x": 6,
        "y": 6
      },
      {
        "x": 7,
        "y": 0
      },
      {
        "x": 7,
        "y": 6
      },
      {
        "x": 8,
        "y": 0
      },
      {
        "x": 8,
        "y": 6
      },
      {
        "x": 9,
        "y": 0
      },
      {
        "x": 9,
        "y": 6
      },
      {
        "x": 10,
        "y": 0
      },
      {
        "x": 10,
        "y": 6
      },
      {
        "x": 11,
        "y": 0
      },
      {
        "x": 11,
        "y": 6
      },
      {
        "x": 12,
        "y": 0
      },
      {
        "x": 12,
        "y": 6
      },
      {
        "x": 13,
        "y": 0
      },
      {
        "x": 13,
        "y": 6
      },
      {
        "x": 14,
        "y": 0
      },
      {
        "x": 14,
        "y": 6
      },
      {
        "x": 0,
        "y": 1
      },
      {
        "x": 0,
        "y": 2
      },
      {
        "x": 0,
        "y": 3
      },
      {
        "x": 0,
        "y": 4
      },
      {
        "x": 0,
        "y": 5
      },
      {
        "x": 14,
        "y": 1
      },
      {
        "x": 14,
        "y": 2
      },
      {
        "x": 14,
        "y": 3
      },
      {
        "x": 14,
        "y": 4
      },
      {
        "x": 14,
        "y": 5
      }
    ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level17.json
{
  "width" : 18,
  "height" : 14,
  "playableArea" : {
    "width" : 5,
    "height" : 5,
    "x" : 0,
    "y" : 0
  },
  "cells" : {
    "mover" : [ ],
    "generator" : [ {
      "orientation" : "right",
      "x" : 0,
      "y" : 0
    }, {
      "orientation" : "right",
      "x" : 1,
      "y" : 0
    }, {
      "orientation" : "down",
      "x" : 2,
      "y" : 0
    }, {
      "orientation" : "left",
      "x" : 4,
      "y" : 0
    } ],
    "rotator" : [ ],
    "block" : [ ],
    "enemy" : [ {
      "x" : 3,
      "y" : 10
    }, {
      "x" : 3,
      "y" : 12
    }, {
      "x" : 1,
      "y" : 13
    }, {
      "x" : 3,
      "y" : 11
    }, {
      "x" : 4,
      "y" : 11
    }, {
      "x" : 2,
      "y" : 12
    }, {
      "x" : 4,
      "y" : 12
    }, {
      "x" : 5,
      "y" : 12
    }, {
      "x" : 0,
      "y" : 13
    }, {
      "x" : 5,
      "y" : 10
    }, {
      "x" : 6,
      "y" : 11
    }, {
      "x" : 2,
      "y" : 13
    }, {
      "x" : 1,
      "y" : 10
    }, {
      "x" : 1,
      "y" : 12
    }, {
      "x" : 2,
      "y" : 10
    }, {
      "x" : 6,
      "y" : 12
    }, {
      "x" : 5,
      "y" : 13
    }, {
      "x" : 4,
      "y" : 10
    }, {
      "x" : 0,
      "y" : 11
    }, {
      "x" : 0,
      "y" : 12
    }, {
      "x" : 1,
      "y" : 11
    }, {
      "x" : 6,
      "y" : 13
    }, {
      "x" : 3,
      "y" : 13
    }, {
      "x" : 4,
      "y" : 13
    }, {
      "x" : 0,
      "y" : 10
    }, {
      "x" : 6,
      "y" : 10
    }, {
      "x" : 5,
      "y" : 11
    }, {
      "x" : 2,
      "y" : 11
    } ],
    "wall" : [ {
      "x" : 6,
      "y" : 7
    }, {
      "x" : 8,
      "y" : 6
    }, {
      "x" : 0,
      "y" : 9
    }, {
      "x" : 5,
      "y" : 8
    }, {
      "x" : 7,
      "y" : 6
    }, {
      "x" : 1,
      "y" : 6
    }, {
      "x" : 4,
      "y" : 7
    }, {
      "x" : 5,
      "y" : 9
    }, {
      "x" : 4,
      "y" : 6
    }, {
      "x" : 7,
      "y" : 5
    }, {
      "x" : 3,
      "y" : 7
    }, {
      "x" : 1,
      "y" : 7
    }, {
      "x" : 4,
      "y" : 5
    }, {
      "x" : 2,
      "y" : 8
    }, {
      "x" : 6,
      "y" : 9
    }, {
      "x" : 8,
      "y" : 8
    }, {
      "x" : 9,
      "y" : 8
    }, {
      "x" : 2,
      "y" : 5
    }, {
      "x" : 3,
      "y" : 9
    }, {
      "x" : 1,
      "y" : 8
    }, {
      "x" : 1,
      "y" : 5
    }, {
      "x" : 0,
      "y" : 6
    }, {
      "x" : 6,
      "y" : 8
    }, {
      "x" : 7,
      "y" : 7
    }, {
      "x" : 2,
      "y" : 6
    }, {
      "x" : 3,
      "y" : 6
    }, {
      "x" : 5,
      "y" : 6
    }, {
      "x" : 0,
      "y" : 5
    }, {
      "x" : 8,
      "y" : 9
    }, {
      "x" : 3,
      "y" : 5
    }, {
      "x" : 6,
      "y" : 5
    }, {
      "x" : 8,
      "y" : 5
    }, {
      "x" : 4,
      "y" : 9
    }, {
      "x" : 9,
      "y" : 6
    }, {
      "x" : 5,
      "y" : 5
    }, {
      "x" : 7,
      "y" : 9
    }, {
      "x" : 1,
      "y" : 9
    }, {
      "x" : 3,
      "y" : 8
    }, {
      "x" : 0,
      "y" : 8
    }, {
      "x" : 0,
      "y" : 7
    }, {
      "x" : 9,
      "y" : 9
    }, {
      "x" : 8,
      "y" : 7
    }, {
      "x" : 4,
      "y" : 8
    }, {
      "x" : 7,
      "y" : 8
    }, {
      "x" : 9,
      "y" : 7
    }, {
      "x" : 2,
      "y" : 7
    }, {
      "x" : 2,
      "y" : 9
    }, {
      "x" : 5,
      "y" : 7
    }, {
      "x" : 9,
      "y" : 5
    }, {
      "x" : 6,
      "y" : 6
    } ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level03.json
{
  "width": 8,
  "height": 5,
  "playableArea": {
    "width": 4,
    "height": 5,
    "x": 0,
    "y": 0
  },
  "cells": {
    "mover": [
      {
        "orientation": "top",
        "x": 3,
        "y": 1
      }
    ],
    "rotator": [
      {
        "rotation": "clockwise",
        "x": 1,
        "y": 3
      }
    ],
    "enemy": [
      {
        "x": 6,
        "y": 2
      }
    ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level27.json
{
  "width" : 9,
  "height" : 15,
  "playableArea" : {
    "width" : 9,
    "height" : 6,
    "x" : 0,
    "y" : 0
  },
  "cells" : {
    "mover" : [ {
      "orientation" : "right",
      "x" : 2,
      "y" : 1
    }, {
      "orientation" : "top",
      "x" : 1,
      "y" : 12
    }, {
      "orientation" : "down",
      "x" : 8,
      "y" : 12
    } ],
    "generator" : [ {
      "orientation" : "right",
      "x" : 2,
      "y" : 12
    }, {
      "orientation" : "left",
      "x" : 6,
      "y" : 12
    } ],
    "rotator" : [ {
      "rotation" : "counterclockwise",
      "x" : 0,
      "y" : 10
    }, {
      "rotation" : "counterclockwise",
      "x" : 1,
      "y" : 14
    }, {
      "rotation" : "clockwise",
      "x" : 6,
      "y" : 1
    }, {
      "rotation" : "counterclockwise",
      "x" : 1,
      "y" : 10
    }, {
      "rotation" : "clockwise",
      "x" : 7,
      "y" : 10
    }, {
      "rotation" : "clockwise",
      "x" : 8,
      "y" : 10
    }, {
      "rotation" : "counterclockwise",
      "x" : 0,
      "y" : 14
    }, {
      "rotation" : "clockwise",
      "x" : 8,
      "y" : 14
    }, {
      "rotation" : "clockwise",
      "x" : 7,
      "y" : 14
    } ],
    "block" : [ ],
    "enemy" : [ {
      "x" : 4,
      "y" : 11
    }, {
      "x" : 4,
      "y" : 9
    }, {
      "x" : 4,
      "y" : 7
    }, {
      "x" : 4,
      "y" : 10
    }, {
      "x" : 4,
      "y" : 8
    } ],
    "wall" : [ {
      "x" : 2,
      "y" : 8
    }, {
      "x" : 6,
      "y" : 6
    },{
      "x" : 2,
      "y" : 13
    }, {
      "x" : 4,
      "y" : 13
    }, {
      "x" : 3,
      "y" : 13
    }, {
      "x" : 2,
      "y" : 9
    }, {
      "x" : 2,
      "y" : 11
    }, {
      "x" : 2,
      "y" : 6
    }, {
      "x" : 0,
      "y" : 6
    }, {
      "x" : 6,
      "y" : 14
    },{
      "x" : 6,
      "y" : 13
    },{
      "x" : 2,
      "y" : 10
    }, {
      "x" : 3,
      "y" : 4
    }, {
      "x" : 2,
      "y" : 14
    },{
      "x" : 6,
      "y" : 10
    }, {
      "x" : 6,
      "y" : 11
    }, {
      "x" : 2,
      "y" : 3
    }, {
      "x" : 5,
      "y" : 4
    }, {
      "x" : 4,
      "y" : 4
    }, {
      "x" : 6,
      "y" : 8
    }, {
      "x" : 8,
      "y" : 9
    }, {
      "x" : 6,
      "y" : 9
    }, {
      "x" : 2,
      "y" : 7
    }, {
      "x" : 6,
      "y" : 3
    }, {
      "x" : 7,
      "y" : 9
    }, {
      "x" : 7,
      "y" : 6
    }, {
      "x" : 0,
      "y" : 9
    },{
      "x" : 6,
      "y" : 7
    }, {
      "x" : 8,
      "y" : 6
    }, {
      "x" : 1,
      "y" : 6
    }, {
      "x" : 1,
      "y" : 9
    }, {
      "x" : 4,
      "y" : 12
    }, {
      "x" : 5,
      "y" : 13
    }]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level22.json
{
  "width" : 13,
  "height" : 6,
  "playableArea" : {
    "width" : 4,
    "height" : 5,
    "x" : 0,
    "y" : 0
  },
  "cells" : {
    "mover" : [ {
      "orientation" : "down",
      "x" : 1,
      "y" : 0
    }, {
      "orientation" : "down",
      "x" : 0,
      "y" : 3
    } ],
    "generator" : [ {
      "orientation" : "top",
      "x" : 3,
      "y" : 1
    } ],
    "rotator" : [ {
      "rotation" : "counterclockwise",
      "x" : 2,
      "y" : 1
    } ],
    "block" : [ ],
    "enemy" : [ {
      "x" : 9,
      "y" : 2
    }, {
      "x" : 12,
      "y" : 1
    }, {
      "x" : 9,
      "y" : 1
    }, {
      "x" : 6,
      "y" : 2
    }, {
      "x" : 12,
      "y" : 2
    }, {
      "x" : 6,
      "y" : 1
    } ],
    "wall" : [ ]
  }
}

=== cake-lier/PPS-20-caw/src/main/resources/levels/level05.json
{
  "width": 13,
  "height": 8,
  "playableArea": {
    "width": 10,
    "height": 3,
    "x": 0,
    "y": 0
  },
  "cells": {
    "mover": [
      {
        "orientation": "down",
        "x": 4,
        "y": 0
      },
      {
        "orientation": "down",
        "x": 7,
        "y": 0
      },
      {
        "orientation": "down",
        "x": 1,
        "y": 6
      }
    ],
    "block": [
      {
        "push": "both",
        "x": 0,
        "y": 0
      },
      {
        "push": "both",
        "x": 6,
        "y": 1
      },
      {
        "push": "vertical",
        "x": 2,
        "y": 6
      }
    ],
    "enemy": [
      {
        "x": 11,
        "y": 6
      },
      {
        "x": 12,
        "y": 6
      }
    ]
  }
}
